pkg: github.com/chenjiahao-stl/calf-auth
name: calf-auth
description: user-auth
enable_keyauth: false
enable_mysql: false
enable_mongodb: true
gen_example: true
http_framework: go-restful
enable_cache: false
